# Generated by Django 4.0 on 2022-07-10 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0004_connections'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Connections',
            new_name='Connection',
        ),
    ]
