# Generated by Django 4.0 on 2022-07-12 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_connections_connection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Connection',
        ),
    ]
