# Generated by Django 4.0 on 2022-07-20 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_delete_connection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='admins',
        ),
    ]
