# Generated by Django 4.0 on 2022-07-21 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_chat_admins'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='inivateHash',
            field=models.CharField(default='sZiUyBDrCZb4YkMc3ymB2g', max_length=22, unique=True),
        ),
    ]
