# Generated by Django 4.0 on 2022-07-21 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_chat_inivatehash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='inivateHash',
            field=models.CharField(default='K6cXrgnu_gT--6uEEKKLGg', max_length=22, unique=True),
        ),
    ]
