# Generated by Django 4.0 on 2022-07-21 10:01

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_chat_inivatehash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='inivateHash',
            field=models.CharField(default=main.models.generate_hash, max_length=22, unique=True),
        ),
    ]
