# Generated by Django 4.0 on 2022-07-21 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_rename_inivatehash_chat_invatehash'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='invateHash',
            new_name='inviteHash',
        ),
    ]
